# Grouping Observations Using Clustering

If you know that you have k groups, you can use k-means clustering to group similar
observations and output a new feature containing each observation’s group member‐
ship:

In [1]:
# Load libraries
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
# Make simulated feature matrix
features, _ = make_blobs(n_samples = 50,
 n_features = 2,
 centers = 3,
 random_state = 1)

features

array([[ -9.87755355,  -3.33614544],
       [ -7.28721033,  -8.35398617],
       [ -6.94306091,  -7.0237442 ],
       [ -7.44016713,  -8.79195851],
       [ -6.64138783,  -8.07588804],
       [ -0.79415228,   2.10495117],
       [ -2.76017908,   5.55121358],
       [ -9.94690475,  -4.59034419],
       [ -0.52579046,   3.3065986 ],
       [ -1.98197711,   4.02243551],
       [ -5.8659643 ,  -7.96807169],
       [ -6.83478745,  -7.39121692],
       [ -6.74924724, -10.17542932],
       [-10.75211044,  -2.70048039],
       [ -8.50899599,  -8.65769397],
       [ -2.33080604,   4.39382527],
       [ -0.19745197,   2.34634916],
       [  0.08525186,   3.64528297],
       [-10.20660674,  -3.36672536],
       [ -9.15872909,  -3.02224647],
       [ -1.34052081,   4.15711949],
       [ -1.83198811,   3.52863145],
       [ -9.80679702,  -1.85309341],
       [ -0.75870396,   3.72276201],
       [-11.1402307 ,  -4.30269127],
       [ -7.8121371 ,  -5.34984488],
       [ -2.35122066,   4.00973634],
       [ -6.87832079,  -7.74317646],
       [ -1.78245013,   3.47072043],
       [ -7.3710862 ,  -7.32525346],
       [ -7.73554447,  -7.77566432],
       [-11.11502285,  -3.71893285],
       [ -9.69754218,  -4.30559839],
       [-10.18954806,  -4.84097751],
       [ -2.18773166,   3.33352125],
       [ -2.34673261,   3.56128423],
       [ -1.92744799,   4.93684534],
       [-10.7448708 ,  -2.26089395],
       [ -6.86658246,  -8.03421946],
       [ -7.51201075,  -6.9287204 ],
       [ -6.90484511,  -7.27705918],
       [ -1.61734616,   4.98930508],
       [ -0.75796919,   4.90898421],
       [ -9.48478268,  -4.25144138],
       [ -7.40873586,  -8.10963125],
       [ -9.50919436,  -4.02892026],
       [ -8.33791033,  -3.21130439],
       [ -9.71212518,  -3.06820738],
       [ -8.86608312,  -2.43353173],
       [ -7.68488303,  -7.45519607]])

In [2]:
# Create DataFrame
dataframe = pd.DataFrame(features, columns=["feature_1", "feature_2"])
dataframe

    feature_1  feature_2
0   -9.877554  -3.336145
1   -7.287210  -8.353986
2   -6.943061  -7.023744
3   -7.440167  -8.791959
4   -6.641388  -8.075888
5   -0.794152   2.104951
6   -2.760179   5.551214
7   -9.946905  -4.590344
8   -0.525790   3.306599
9   -1.981977   4.022436
10  -5.865964  -7.968072
11  -6.834787  -7.391217
12  -6.749247 -10.175429
13 -10.752110  -2.700480
14  -8.508996  -8.657694
15  -2.330806   4.393825
16  -0.197452   2.346349
17   0.085252   3.645283
18 -10.206607  -3.366725
19  -9.158729  -3.022246
20  -1.340521   4.157119
21  -1.831988   3.528631
22  -9.806797  -1.853093
23  -0.758704   3.722762
24 -11.140231  -4.302691
25  -7.812137  -5.349845
26  -2.351221   4.009736
27  -6.878321  -7.743176
28  -1.782450   3.470720
29  -7.371086  -7.325253
30  -7.735544  -7.775664
31 -11.115023  -3.718933
32  -9.697542  -4.305598
33 -10.189548  -4.840978
34  -2.187732   3.333521
35  -2.346733   3.561284
36  -1.927448   4.936845
37 -10.744871  -2.260894
38  -6.866582  -8.034219
39  -7.512011  -6.928720
40  -6.904845  -7.277059
41  -1.617346   4.989305
42  -0.757969   4.908984
43  -9.484783  -4.251441
44  -7.408736  -8.109631
45  -9.509194  -4.028920
46  -8.337910  -3.211304
47  -9.712125  -3.068207
48  -8.866083  -2.433532
49  -7.684883  -7.455196

In [3]:
# Make k-means clusterer
clusterer = KMeans(3, random_state=0)

In [4]:
# Fit clusterer
clusterer.fit(features)

KMeans(n_clusters=3, random_state=0)

In [5]:
dataframe["group"] = clusterer.predict(features)

In [6]:
dataframe

    feature_1  feature_2  group
0   -9.877554  -3.336145      0
1   -7.287210  -8.353986      2
2   -6.943061  -7.023744      2
3   -7.440167  -8.791959      2
4   -6.641388  -8.075888      2
5   -0.794152   2.104951      1
6   -2.760179   5.551214      1
7   -9.946905  -4.590344      0
8   -0.525790   3.306599      1
9   -1.981977   4.022436      1
10  -5.865964  -7.968072      2
11  -6.834787  -7.391217      2
12  -6.749247 -10.175429      2
13 -10.752110  -2.700480      0
14  -8.508996  -8.657694      2
15  -2.330806   4.393825      1
16  -0.197452   2.346349      1
17   0.085252   3.645283      1
18 -10.206607  -3.366725      0
19  -9.158729  -3.022246      0
20  -1.340521   4.157119      1
21  -1.831988   3.528631      1
22  -9.806797  -1.853093      0
23  -0.758704   3.722762      1
24 -11.140231  -4.302691      0
25  -7.812137  -5.349845      2
26  -2.351221   4.009736      1
27  -6.878321  -7.743176      2
28  -1.782450   3.470720      1
29  -7.371086  -7.325253      2
30  -7.735544  -7.775664      2
31 -11.115023  -3.718933      0
32  -9.697542  -4.305598      0
33 -10.189548  -4.840978      0
34  -2.187732   3.333521      1
35  -2.346733   3.561284      1
36  -1.927448   4.936845      1
37 -10.744871  -2.260894      0
38  -6.866582  -8.034219      2
39  -7.512011  -6.928720      2
40  -6.904845  -7.277059      2
41  -1.617346   4.989305      1
42  -0.757969   4.908984      1
43  -9.484783  -4.251441      0
44  -7.408736  -8.109631      2
45  -9.509194  -4.028920      0
46  -8.337910  -3.211304      0
47  -9.712125  -3.068207      0
48  -8.866083  -2.433532      0
49  -7.684883  -7.455196      2